kind: Deployment
apiVersion: apps/v1
metadata:
  name: qod-api
  labels:
    app: qod-api
    app.kubernetes.io/component: qod-api
    app.kubernetes.io/instance: qod-api
    app.kubernetes.io/name: qod-api
    app.kubernetes.io/part-of: QOD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qod-api
        deployment: qod-api
    spec:
      containers:
        - name: qod-api
          image: 'docker.io/kalyan1981/qod-api:latest'
          envFrom:
            - secretRef:
                name: qod-db-credentials
            - secretRef:
                name: qod-db-credentials
            - secretRef:
                name: qod-db-credentials
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
